# Partly taken from https://github.com/mortbopet/Ripes/blob/master/.github/workflows/linux-release.yml
name: Release setup

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-20.04

    permissions: write-all

    steps:

    - name: Job info
      run: |
        echo "GitHub Ref: ${{ github.ref }}"
        echo "Event: ${{ github.event }}"

    - name: get container ready for build
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q --force-yes \
        texlive texlive-latex-extra

    - name: checkout sources
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: prepare release
      run:
        ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: Resume PDF
        path: resume.pdf

    - name: get current date
      id: time
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY_MM_DD"

    - name: continuous release
      uses: softprops/action-gh-release@v1
      with:
        files: resume.pdf
        name: Resume(${{ steps.time.outputs.time }})
        tag_name: ${{ steps.time.outputs.time }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

